services:
  LoopOfLegendServer:
    image: ghcr.io/theodrosrun/loop_of_legends_server:v1.0.0
    command:
      - --unicast-host=127.0.0.1
      - --unicast-port=10000
      - --multicast-host=239.1.1.1
      - --multicast-port=20000
      - --multicast-stream-host=239.1.1.2
      - --multicast-stream-port=20001
  client:
    image: ghcr.io/theodrosrun/loop_of_legends_client:v1.0.0
    command:
      - --unicast-host=127.0.0.1
      - --unicast-port=10000
      - --multicast-host=239.1.1.1
      - --multicast-port=20000
    depends_on:
      - LoopOfLegendServer
    stdin_open: true
    tty: true
  viewer:
    image: ghcr.io/theodrosrun/loop_of_legends_viewer:v1.0.0
    command:
      - --multicast-stream-host=239.1.1.2
      - --multicast-stream-port=20001
    depends_on:
      - LoopOfLegendServer
    stdin_open: true
    tty: true