services:
  LoopOfLegendServer:
    image: saloon_server:v1.0.0
    command:
      - --Adapter=eth0
  client1:
    image: saloon_client:v1.0.0
    command:
      - --Adapter=eth0
      - --DefaultHost=SaloonServer
    depends_on:
      - LoopOfLegendServer
    stdin_open: true
    tty: true
  client2:
    image: saloon_client:v1.0.0
    command:
      - --Adapter=eth0
      - --DefaultHost=SaloonServer
    depends_on:
      - LoopOfLegendServer
    stdin_open: true
    tty: true