services:
  LoopOfLegendServer:
    image: loop_of_legends_server:v1.0.0
    command:
      - --Adapter=eth0
  client:
    image: loop_of_legends_client:v1.0.0
    command:
      - --Adapter=eth0
      - --DefaultHost=LoopOfLegendServer
    depends_on:
      - LoopOfLegendServer
    stdin_open: true
    tty: true
  viewer:
    image: loop_of_legends_viewer:v1.0.0
    command:
      - --Adapter=eth0
      - --DefaultHost=LoopOfLegendServer
    depends_on:
      - LoopOfLegendServer
    stdin_open: true
    tty: true